[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  included_files = ["views/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

